### ISSUE TITLE
የሚሸጥ ቦታ

### ISSUE THREAD

**Issue by Soliarity** [AppLinks/Samples#7]
ለመኖሪያ ቤት የግንባታ ፍቃድ ያለው 140 ካሬ ስፋት ያለው ቦታ ጣፎ ናስ ፉድ ጀርባ (ከCCD የመኖሪያ መንደር ፊት ለፊት) ለመግዛት ከፈለጉ Solid_water19@yahoo.com ላይ ይፆፉልኝ ወይም 0912857477 ይደውሉ

**Comment by tintersniffer** [comment]
tintersniffer@users.noreply.github.com
